version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:22.19.0

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run: ./build.sh
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/
